# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e301cd538bc79e462c57636c0bc08afca6740068f2bc31b394d4bdb7c3216703f3f85e351def1b3f4c7f67edf25b143fcac52044cd160cbf3c568d65882f58a

test:
  secret_key_base: 282333a874d42b5a39de4c0d14b20131a9a86974091acd168ba06b2c2c5fabcd50d030e4dbe4d31c02db1ddd34f8d4ee51be10cb170f119912879a7dc1d0ad38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
